import Head from "next/head";
import About from "../components/about/About";
import CutsomButton from "../components/common/button/CutsomButton";
import { CustomHeader, CustomText } from "../components/common/text/CustomText";
import {
  GeneralWrapper,
  GlobalStyle,
  TitleHeader,
} from "../globalStyle/GlobalStyle";

export default function Home() {
  return (
    <div>
      <GlobalStyle />
      <Head>
        <title>Mubarak | Web developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GeneralWrapper>
        <About />
      </GeneralWrapper>
    </div>
  );
}
